FROM docker.io/library/ubuntu:jammy

RUN apt update && \
    apt install curl

RUN curl -LO https://dl.k8s.io/release/v1.24.0/bin/linux/amd64/kubectl && \
    chmod +x kubectl && \
    mkdir -p ~/.local/bin && \
    mv ./kubectl ~/.local/bin/kubectl

RUN mkdir -p /kubectl/.config

WORKDIR /kubectl