FROM docker.io/redhat/ubi9:latest

RUN adduser --system --home /kubernetes --shell /bin/bash --user-group --uid 1001 kubernetes

ARG KUBE_VERSION

RUN curl -LO https://dl.k8s.io/release/v${KUBE_VERSION}/bin/linux/amd64/kubectl && \
    mkdir -p kubernetes/.local/bin && \
    mv ./kubectl /kubernetes/.local/bin/kubectl && \
    chown kubernetes:kubernetes -R /kubernetes && \
    chmod 100 /kubernetes/.local/bin/kubectl

USER 1001

RUN echo 'export PATH=".local/bin/:$PATH"' >> /kubernetes/.bashrc && \
    mkdir /kubernetes/.kube

WORKDIR /kubernetes

ENTRYPOINT [ "/bin/bash" ]